# -*- coding: utf-8 -*-
"""assignment_saylani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTcNHokOIhc3ESZVARMDX5sI8njaxlbm
"""

# Q1
city_a_t = float(input("Enter temperature of City A (°C): "))
city_b_t = float(input("Enter temperature of City B (°C): "))

if city_a_t > city_b_t:
    print("City A is hotter than City B.")


elif city_a_t < city_b_t:
    print("City A is cooler than City B.")

elif city_a_t == city_b_t:
    print("Both cities have the same temperature.")

else:
    print("Invalid input!")

# Q2
to_bill=int(input("enter the total bill amount"))
num_people=int(input("enter the number of people  "))

share= to_bill/num_people

print(f"Total Bill: ${to_bill:}")
print(f"Number of People: {num_people}")
print(f"Each Person Pays: ${share:}")

# Q3
name= input("enter the name :")
color = input("enter the favourite color :")
num = input("enter the  favourite number:")

data= f"{name}! your favurite colour is {color} you favurite number is {num}"

print(data)

# Q4
num1=int(input("enter the number first:"))
num2=int(input("enter the number second:"))
if num1>num2:
  print("number first is greater than second:")

elif num1<num2:
  print("number first is less than second:")

else:
  print("number are equal: ")

if num1 % 2 == 0 and num2 % 2 == 0:
    print("Both numbers are even:")

elif num1 % 2 != 0 and num2 % 2 != 0:
    print("Both numbers are odd:")
else:
    print("The numbers are mixed:")

# Q5
length =float(input("enter the length of rectangle :"))
width = float(input("enter the width of rectange :"))

area = length * width
pera= 2 * (length + width)
print(f"""
      Length:{length}
      Width: {width}
      Area: {area}
      Pera: {pera}
""")

# Q6
ageA=int(input("enter the age of person one:"))
ageB=int(input("enter the age of person two:"))

difference =abs(ageA - ageB)

print(f"The age difference between Person 1 and Person 2 is: {difference} years.")

#Q7
days = int(input("Enter the number of days: "))
seconds = days * 24 * 60 * 60
print(f"{days} days are equal to {seconds} seconds.")

# Q8
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
operator = input("Enter the operator (+, -, *, /): ")

if operator == '+':
    result = num1 + num2

elif operator == '-':
    result = num1 - num2

elif operator == '*':
    result = num1 * num2

elif operator == '/':
    if num2 != 0:
        result = num1 / num2

    else:
        result = "Error! Division by zero is not allowed."


print(f"{num1} {operator} {num2} = {result}")

# Q9
# Sum of Even Numbers in a Range only even num plus

start = int(input("Enter the start num: "))
end = int(input("Enter the end num: "))

even_sum = 0

for num in range(start, end + 1):
    if num % 2 == 0:
        even_sum += num

print(f"The sum of even numbers between {start} and {end} is {even_sum}.")

# Q10
number=int(input("enter the number:"))
range=int(input("enter the range:"))

multi=number*range

print(f"the multiplication is:{multi}")

# Q11
num = input("Enter a positive integer: ")
count = 0
for digit in num:
    count += 1
print(f"the number is  {num} has {count}  digit");

# Q12
password = input("Enter your password: ")

upper = 0
lower = 0
digit = 0
for ch in password:
    if ch.isupper():
        upper += 1
    elif ch.islower():
        lower += 1
    elif ch.isdigit():
        digit += 1
print(f"Uppercase letters: {upper}")
print(f"Lowercase letters: {lower}")
print(f"Numbers: {digit}")


if len(password) >= 8 and upper > 0 and lower > 0 and digit > 0:
    print("Your password is strong ")
elif len(password) >= 6 and (upper > 0 or lower > 0) and digit > 0:
    print("Your password is medium ")
else:
    print("Your password is weak ")

# Q13
num_items = int(input("Number of items purchased: "))
print("*" * num_items)

sentence = input("Enter a sentence and :")
character = input("Enter a character")

count = 0
for char in sentence:
  if char == character:

    count +=1

print(f"the character '{character}' appears {count} times in a sentence ")

# Q15
print("Celsius\tFahrenheit")

for celsius in range(0, 20, 5):
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}°C = {fahrenheit:.1f}°F")

# Q16
balance = float(input("Enter your initial balance: "))
months = int(input("Enter number of months: "))


for month in range(1, months + 1):
    balance += balance * 0.05
    print(f"Month {month}: {balance:.2f}")